apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-config
data:
  config.yaml: |
    {{ .Files.Get "jenkins-config/config.yaml" | indent 10 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-plugins
data:
  plugins.txt: |
    {{ .Files.Get "jenkins-config/plugins.txt" | indent 10 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-groovy-scripts
data:
  init.groovy: |
    {{ .Files.Get "jenkins-config/init.groovy" | indent 8 }}
