kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      protocol: TCP
      port: {{ .Values.whanos.jenkins.port }}
      name: external-access
  selector:
    app: jenkins
