apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "whanos.fullname" . }}-registry-pvc
    labels:
        app: {{ include "whanos.name" . }}
        chart: {{ include "whanos.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.registry.storageSize }}
