jenkins:
  systemMessage: "Welcome to the Tux-Inc Whanos-powered Jenkins instance!"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"

  securityRealm:
    local:
      allowsSignup: false
    users:
      - id: "admin"
        name: "Administrator"
        password: ${JENKINS_ADMIN_PASSWORD}

  security:
    globalJobDslSecurityConfiguration:
      useScriptSecurity: false

  jobs:
    - file: /jenkins/job_dsl.groovy