---

- name: Create Kubernetes addon directory
  file:
    path: "/etc/kubernetes/network"
    state: directory

- name: "Copy calico YAML files"
  template:
    src: "{{ item }}"
    dest: "/etc/kubernetes/network/{{ item | basename | regex_replace('\\.j2','') }}"
  with_fileglob:
    - ../templates/calico*.j2

- name: "Check calico daemonset is working"
  shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf wait --for=condition=ready pod -l k8s-app=calico-node --all-namespaces --timeout=300s
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: check_net
  ignore_errors: true
  changed_when: false

- name: "Create calico network daemonset"
  when: check_net is failed
  command: kubectl create --kubeconfig=/etc/kubernetes/admin.conf -f /etc/kubernetes/network/
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
